---
title: "Gupta"
author: "Dmitry Zotikov"
date: "May 22, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
AAPL <- read_csv("../../data/AAPL.csv",
                 col_types = cols(Date = col_date(format = "%Y-%m-%d")))
plot(Close ~ Date, data=AAPL, subset = AAPL$Date >= '2004-09-13', type='o', col='blue')

source('../models/norm_hmm.R')
source('../util/modsel.R')
```

## On returns

```{r}
xx <- (AAPL$'Adj Close' -  AAPL$Open) /  AAPL$Open
xx.train <- xx[AAPL$Date < '2004-09-13']
plot(xx.train, type='o', col='blue')
plot(xx, type='o', col='blue')
acf(xx.train, length(xx.train))
acf(xx, length(xx))
hist(xx.train, breaks=20)
hist(xx, breaks=20)
stripchart(xx.train, method='jitter')
m <- 4
km <- kmeans(xx.train, m, iter.max=20, nstart = 10)
for (i in 1:m) {
  stripchart(xx.train[km$cluster==i], col=i+1, method='jitter',
             xlim=c(min(xx.train), max(xx.train)))
  par(new=TRUE)
}
par(new=FALSE)

stripchart(xx, method='jitter')
m <- 4
km <- kmeans(xx, m, iter.max=20, nstart = 10)
for (i in 1:m) {
  stripchart(xx[km$cluster==i], col=i+1, method='jitter',
             xlim=c(min(xx), max(xx)))
  par(new=TRUE)
}
par(new=FALSE)
selectModelIc(NormHmm, xx.train, 6, TRUE, r=8) # 2, 1
hmm <- NormHmm(2, xx.train, r=3, A.init='sec.diag')
print(hmm)
hmm$fit(xx.train)
print(hmm)

train.idx <- which.min(AAPL$Date < '2004-09-13')
fc.len <- sum(!AAPL$Date < '2004-09-13')
# fc <- numeric(fc.len)
fc <- matrix(0, 3, fc.len)
latency <- 10
set.seed(1)
for (h in 0:(fc.len-1)) {
  cat(h, '\n')
  xx.train <- xx[1:(train.idx+h)]
  hmm <- NormHmm(2, xx.train, r=3, A.init='sec.diag')
  hmm$fit(xx.train)
  # print(hmm)
  x.probes <- seq(min(xx.train)*1.5, max(xx.train)*1.5, length.out=50)
  T.train <- length(xx.train)
  # fc[h+1] <- hmm$forecast(xx.train, x.probes = x.probes, 1, 'mode')$forecast
  # fc[1,h+1] <- hmm$forecast(xx.train[(T.train-latency-1):T.train],
  #                           x.probes = x.probes, 1, 'mode')$forecast
  # fc[2,h+1] <- hmm$forecast(xx.train[(T.train-latency-1):T.train],
  #                           x.probes = x.probes, 1, 'median')$forecast
  # fc[3,h+1] <- hmm$forecast(xx.train[(T.train-latency-1):T.train],
  #                           x.probes = x.probes, 1, 'mean')$forecast
  fc[1,h+1] <- hmm$forecast(xx.train,
                            x.probes = x.probes, 1, 'mode')$forecast
}

# par(mfrow=c(3,1))
# for (i in 1:3) {
#   plot(xx[train.idx:length(xx)], lty='dashed', type='o', ylim=c(min(xx),max(xx)))
#   par(new=TRUE)
#   plot(fc[i,], type='o', col='blue', ylim=c(min(xx),max(xx)))
# }
# par(mfrow=c(1,1))

xx.close.test <- AAPL$'Adj Close'[AAPL$Date >= '2004-09-13']
xx.open.test <- AAPL$'Open'[AAPL$Date >= '2004-09-13']
fc.close <- t(t(fc) * xx.open.test + xx.open.test)

w.8 <- 5.21
h.8 <- 3.23
w.10 <- 6.51
h.10 <- 4.04
w.12 <- w.10*1.2
h.12 <- h.10*1.2

ylim <- c(min(xx.close.test, fc.close[1,]),
          max(xx.close.test, fc.close[1,]))

# cairo_ps(file="~/Documents/СПбГУ/Диплом/pic/fc-aapl.ps",
#     width=w.12, height=h.12, pointsize=12)
# mar.old <- par()$mar
# par(mar=c(4,4,0,0)+0.1)  # bottom, left, top, right
# plot(AAPL$'Date'[AAPL$Date >= '2004-09-13'], xx.close.test,
#      lty='dashed', type='o', cex=0.5, ylab='Испр. цена закрытия', xlab='Дата',
#      ylim=ylim)
# par(new=TRUE)
# plot(AAPL$'Date'[AAPL$Date >= '2004-09-13'], fc.close[1,],
#      type='o', col='blue', axes=FALSE, ylab='', xlab='', cex=0.5,
#      ylim=ylim)
# legend("topleft",
#        legend = c('Настоящая цена', 'Прогноз'),
#        col = c('black', 'blue'),
#        lty = c('dashed', 'solid'))
# par(mar=mar.old)
# dev.off()

# cairo_ps(file="~/Documents/СПбГУ/Диплом/pic/fc-aapl-open.ps",
#     width=w.12, height=h.12, pointsize=12)
# mar.old <- par()$mar
# par(mar=c(4,4,0,0)+0.1)  # bottom, left, top, right
# plot(AAPL$'Date'[AAPL$Date >= '2004-09-13'], fc.close[1,],
#      type='o', col='blue', cex=0.7,
#      ylab='', xlab='',
#      ylim=ylim)
# par(new=TRUE)
# plot(AAPL$'Date'[AAPL$Date >= '2004-09-13'], xx.open.test,
#      lty='dashed', type='o', pch=0, axes=FALSE, cex=0.7,
#      ylab='Цена', xlab='Дата',
#      ylim=ylim)
# legend("topleft",
#        legend = c('Цена открытия', 'Прогноз цены закрытия'),
#        col = c('black', 'blue'),
#        lty = c('dashed', 'solid'))
# par(mar=mar.old)
# dev.off()

par(mfrow=c(3,1))
for (i in 1:1) {
  plot(xx.close.test, lty='dashed', type='o',
       ylim=c(min(xx.close.test),max(xx.close.test)))
  par(new=TRUE)
  plot(fc.close[i,], type='o', col='blue',
       ylim=c(min(xx.close.test),max(xx.close.test)))
  par(new=TRUE)
  plot(xx.open.test, type='o', pch=0,
       ylim=c(min(xx.close.test),max(xx.close.test)))
}
par(mfrow=c(1,1))
```

## On prices

```{r}
xx <- AAPL$Close
xx.train <- AAPL[AAPL$Date < '2004-09-13', ]$Close
plot(xx.train, type='o', col='blue')
hist(xx, breaks=20, col='grey')
acf(xx.train, length(xx.train))
selectModelIc(NormHmm, xx.train, 6, TRUE, r=8) # xx: 6, xx.train: 3
hmm <- NormHmm(3, xx.train, r=5, A.init='main.diag')
hmm$fit(xx.train)
print(hmm)

# TRAIN only
M <- matrix(0, length(xx.train), 100)
for (i in 1:100) {
  M[,i] <- hmm$genSample(length(xx.train))
}
# matplot(M)
sample.avg <- apply(M, 1, mean)
ylim <- c(min(xx.train, sample.avg), max(xx.train, sample.avg))
plot(xx.train, type='o', col='blue', ylim=ylim)
par(new=TRUE)
plot(sample.avg, type='o', col='red', ylim=ylim)

# h=200
M <- matrix(0, 200, 100)
for (i in 1:100) {
  M[,i] <- hmm$genSample(200)
}
# matplot(M)
sample.avg <- apply(M, 1, mean)
ylim <- c(min(xx[1:200], sample.avg), max(xx[1:200], sample.avg))
plot(xx[1:200], type='o', col='blue', ylim=ylim)
par(new=TRUE)
plot(sample.avg, type='o', col='red', ylim=ylim)

# forecast by 1
## subsequent training

### with latency -- no difference compared to l = T-1 (almost; not by mode)

source('norm_hmm.R')
train.idx <- which.min(AAPL$Date < '2004-09-13')
fc.len <- sum(!AAPL$Date < '2004-09-13')
# fc <- numeric(fc.len)
fc <- matrix(0, 3, fc.len)
latency <- 10
set.seed(1)
for (h in 0:(fc.len-1)) {
  cat(h, '\n')
  xx.train <- xx[1:(train.idx+h)]
  hmm <- NormHmm(6, xx.train, r=5, A.init='main.diag')
  hmm$fit(xx.train)
  # print(hmm)
  x.probes <- seq(min(xx.train)*1.5, max(xx.train)*1.5, by=0.2)
  T.train <- length(xx.train)
  # fc[h+1] <- hmm$forecast(xx.train, x.probes = x.probes, 1, 'mode')$forecast
  fc[1,h+1] <- hmm$forecast(xx.train[(T.train-latency-1):T.train],
                            x.probes = x.probes, 1, 'mode')$forecast
  fc[2,h+1] <- hmm$forecast(xx.train[(T.train-latency-1):T.train],
                            x.probes = x.probes, 1, 'median')$forecast
  fc[3,h+1] <- hmm$forecast(xx.train[(T.train-latency-1):T.train],
                            x.probes = x.probes, 1, 'mean')$forecast
}

par(mfrow=c(3,1))
for (i in 1:3) {
  plot(xx[train.idx:length(xx)], lty='dashed', type='o', ylim=c(35,71))
  par(new=TRUE)
  plot(fc[i,], type='o', col='blue', ylim=c(35,71))
}
par(mfrow=c(1,1))

# returns

plot(diff(xx), type='o', col='blue')
mean(diff(xx))
r <- numeric(0)
for (l in 1:100) r[l] <- mean(diff(xx, lag=l))
plot(r, type='o', col='blue')

plot(diff(log(xx)),  type='o', col='blue')
```

