---
title: "main"
author: "Dmitry Zotikov"
date: "March 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TODO:

- E, D of norm
- MC ACF
- Fit MC
- Find MC stationary distribution
- stationary mc distribution -- when important? one extra multiplication is
  not a big deal...
- NULL => stationary
- hmm pdf in the case of a stationary MC
- HMM for m = 1 (make sure it's working)
- sd or sd^2?
- hist of gen.sample -- unimodal??
- test on model solution
- compare pois hmm component densities with zuc
- proper initialize, missing(), ...
- optim, constrOptim
- forecast for continuous
- while fitting, check the code; if not 1, act appropriately

- Почитать Hasan и другие статьи по hmm+forecast
- Понять, почему важно иметь предсказание распределения (для геологов) и т.д.
- Задачи, где СММ выбирают модель
- Максимум hist и curve / pdf в графиках

 - fix plotForecast --- xlim via x.probes

 - prediction on smoothed ts?
 - is hmm necessary? if acf != 0, just work with differences
 
 - Кросс-валидация vs AIC/BIC
 - Документ по IC
 - Доверительный интервал через профили
 - Документ по прогнозу: Hong; Hassan
 - $\max_{x}\P(\xi_{T+h}=x\mid\mathbf{x})$
 - Протестировать на модельном решении (нагенерить ряд как смесь тренда, периодики, шума)
 - Ансамбль моделей
 - The state-dependent density functions can also be estimated nonparametrically, hence avoiding the need to make any distributional assumption (Langrock et al., 2015)
 
 - Ссылка на то, когда оценки состоятельны (от НЭ)
 
 * Придумать меру разницы между СММ помимо `MLLK`, если в этом вообще есть необходимость.
 * С помощью категориальной СММ провести повторный анализ текстовых данных как в прошлом году.
    * При помощи алгоритма интраполяции попытаться заполнить пропуски в тексте.
 * Попробовать другие алгоритмы оптимизации, менее подверженные застреванию в локальных минимумах (Nelder-Mead?).
 * Обучить модели со стационарными МЦ.
 * Построить доверительные интервалы для параметров на основе SE.
 * Прогноз по Hassan, Hong
 
 * Ширина доверительного интервала в зависимости от объема выборки :)
