---
title: "Sine forecasting"
author: "Dmitry Zotikov"
date: "March 31, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EQ-Pois forward forecasting

```{r, eval=FALSE, message=FALSE, include=FALSE}
source('import_earthquakes.R')
source('util_plot.R')
source('pois_hmm.R')

xx <- earthquakes.zuc.annual$count
x.probes <- 0:50
h.max <- 16

hmm <- PoisHmm(4, xx)
hmm$fit(xx)
# plotForecastDist(hmm$forecastDist(xx, x.probes, h.max), xx, x.probes)
fc <- hmm$forecast(xx, x.probes, h.max, 'median')
plotForecast(fc, xx, h.max)
```

## EQ-Pois train/test forecasting

```{r, fig.height=10, fig.width=9, message=FALSE, include=FALSE}
source('import_earthquakes.R')
source('util_plot.R')
source('pois_hmm.R')

xx <- earthquakes.zuc.annual$count
x.probes <- 0:50
h.max <- 16

T <- length(xx)
T.train <- T-h.max
xx.train <- xx[1:(T.train)]
xx.true <- xx[(T.train+1):T]
hmm <- PoisHmm(4, xx.train)
set.seed(1)
hmm$fit(xx.train)
plotForecastDist(hmm$forecastDist(xx.train, x.probes, h.max), xx.train, x.probes)
par(mfrow=c(3,1))
for (avg in c('mean', 'median', 'mode')) {
  fc <- hmm$forecast(xx.train, x.probes, h.max, avg)
  plotForecast(fc, xx.train, h.max, xx.true)
  title(avg)
}
par(mfrow=c(1,1))
```

## Sine model forward forecasting

```{r}
source('util_plot.R')
source('norm_hmm.R')
source('modsel.R')
library('forecast')

set.seed(1)
T <- 100
tt <- seq(0, 4*pi, length.out=T)
par(mfrow=c(3, 1))
xx.line <- 1 + 0.5*tt
plot(xx.line, type='l')
xx.sine <- xx.line + sin(2*tt)
plot(xx.sine, type='l')
xx <- xx.sine + runif(100, -2, 2)
xx <- ts(xx)
plot(xx, type='o')
par(mfrow=c(1,1))
acf(xx, T)

# pdf(file="~/Documents/СПбГУ/Диплом/pic/sine-data.pdf",
#     width=6.06, height=4.06, pointsize=12)
# mar.old <- par()$mar
# par(mar=c(2,2,1,0)+0.1)  # bottom, left, top, right
# par(mfrow=c(3, 1))
# plot(xx.line, type='l')
# plot(xx.sine, type='l')
# plot(xx, type='o')
# par(mfrow=c(1,1))
# par(mar=mar.old)
# dev.off()


h.max <- 16
x.probes <- seq(min(xx), max(xx), length.out = 50)

# selectModelIc(NormHmm, xx, 7, TRUE)  # 2
set.seed(1)
hmm <- NormHmm(3, xx)
hmm$fit(xx)
hmm
```

```{r, fig.height=10, fig.width=9}
plotForecastDist(hmm$forecastDist(xx, x.probes, h.max), xx, x.probes)
par(mfrow=c(3,1))
for (avg in c('mean', 'median', 'mode')) {
  fc <- hmm$forecast(xx, x.probes, h.max, avg)
  plotForecast(fc, xx, h.max)
  title(avg)
}
par(mfrow=c(1,1))

# pdf(file="~/Documents/СПбГУ/Диплом/pic/sine-forec-3.pdf",
#     width=6.06, height=4.06, pointsize=12)
# mar.old <- par()$mar
# par(mar=c(2,2,2,1)+0.1)  # bottom, left, top, right
# par(mfrow=c(3,1))
# for (avg in c('mean', 'median', 'mode')) {
#   fc <- hmm$forecast(xx, x.probes, h.max, avg)
#   plotForecast(fc, xx, h.max)
#   title(avg)
# }
# par(mfrow=c(1,1))
# par(mar=mar.old)
# dev.off()

# pdf(file="~/Documents/СПбГУ/Диплом/pic/sine-dist-3.pdf",
#     width=6.06, height=4.06, pointsize=12)
# mar.old <- par()$mar
# par(mar=c(2,2,1.8,1)+0.1)  # bottom, left, top, right
# plotForecastDist(hmm$forecastDist(xx, x.probes, h.max), xx, x.probes)
# par(mar=mar.old)
# dev.off()
```

```{r, eval=FALSE, include=FALSE}
for (m in c(2:8)) {
  set.seed(1)
  hmm <- NormHmm(m, xx)
  hmm$fit(xx)
  par(mfrow=c(3,1))
  for (avg in c('mean', 'median', 'mode')) {
    fc <- hmm$forecast(xx, x.probes, h.max, avg)
    plotForecast(fc, xx, h.max)
    title(paste('m =', m, avg))
  }
  par(mfrow=c(1,1))
}
```


```{r}
auto.arima(xx)
plot(forecast(arima(xx, order=c(1, 1, 1)), h.max))
```

## Sine model with train/test forecasting

```{r}
source('util_plot.R')
source('norm_hmm.R')
source('modsel.R')
library('forecast')

set.seed(1)
T <- 200
tt <- seq(0, 4*pi, length.out=T)
xx <- ts(1 + 0.5*tt + sin(2*tt) + runif(100, -2, 2))

h.max <- 16
T.train <- T-h.max
xx.train <- xx[1:(T.train)]
xx.true <- xx[(T.train+1):T]

x.probes <- seq(min(xx.train), max(xx.train), length.out = 50)
selectModelIc(NormHmm, xx.train, 7, TRUE)  # 4, 2
hmm <- NormHmm(2, xx.train)
set.seed(1)
hmm$fit(xx.train)
hmm
```

```{r, fig.height=10, fig.width=9, message=FALSE}
plotForecastDist(hmm$forecastDist(xx.train, x.probes, h.max), xx.train, x.probes)
par(mfrow=c(3,1))
for (avg in c('mean', 'median', 'mode')) {
  fc <- hmm$forecast(xx.train, x.probes, h.max, avg)
  plotForecast(fc, xx.train, h.max, xx.true)
  title(avg)
}
par(mfrow=c(1,1))

set.seed(1)
hmm <- NormHmm(4, xx.train)
hmm$fit(xx.train)

# pdf(file="~/Documents/СПбГУ/Диплом/pic/sine-forec-test-4.pdf",
#     width=6.06, height=4.06, pointsize=12)
# mar.old <- par()$mar
# par(mar=c(2,2,2,1)+0.1)  # bottom, left, top, right
# par(mfrow=c(3,1))
# for (avg in c('mean', 'median', 'mode')) {
#   fc <- hmm$forecast(xx.train, x.probes, h.max, avg)
#   plotForecast(fc, xx.train[100:length(xx.train)], h.max, xx.true)
#   title(avg)
# }
# par(mfrow=c(1,1))
# par(mar=mar.old)
# dev.off()
```

```{r, eval=FALSE, include=FALSE}
for (m in c(2:7)) {
  set.seed(1)
  hmm <- NormHmm(m, xx.train)
  hmm$fit(xx.train)
  par(mfrow=c(3,1))
  for (avg in c('mean', 'median', 'mode')) {
    fc <- hmm$forecast(xx.train, x.probes, h.max, avg)
    plotForecast(fc, xx.train, h.max, xx.true)
    title(paste('m =', m, avg))
  }
  par(mfrow=c(1,1))
}
```


```{r}
auto.arima(xx.train)
plot(forecast(arima(xx.train, order=c(0, 1, 1)), h.max))
```

### $m=4$

```{r}
hmm <- NormHmm(4, xx.train)
hmm$fit(xx.train)
# plotA(hmm)
hmm
```

```{r, fig.height=10, fig.width=9, message=FALSE}
plotForecastDist(hmm$forecastDist(xx.train, x.probes, h.max), xx.train, x.probes)
par(mfrow=c(3,1))
for (avg in c('mean', 'median', 'mode')) {
  fc <- hmm$forecast(xx.train, x.probes, h.max, avg)
  plotForecast(fc, xx.train, h.max, xx.true)
  title(avg)
}
par(mfrow=c(1,1))
```