---
title: "main"
author: "Dmitry Zotikov"
date: "March 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- E, D of norm
- MC ACF
- Fit MC
- Find MC stationary distribution
- stationary mc distribution -- when important? one extra multiplication is
  not a big deal...
- hmm pdf in the case of a stationary MC
- sd or sd^2?
- hist of gen.sample -- unimodal??
- while fitting, check the code; if not 1, act appropriately
- Задачи, где СММ выбирают модель
- Максимум hist и curve / pdf в графиках
- prediction on smoothed ts?
- Кросс-валидация vs AIC/BIC
- Документ по IC
- Доверительный интервал через профили
- Ансамбль моделей
- The state-dependent density functions can also be estimated nonparametrically, hence avoiding the need to make any distributional assumption (Langrock et al., 2015)
- Ссылка на то, когда оценки состоятельны (от НЭ)
- Попробовать другие алгоритмы оптимизации, менее подверженные застреванию в локальных минимумах (SANN?).
  - nloptr, optim
  - optimizm via Hastie (p.230)
  - BIC vs AIC = p.235
  - Err, $\overline{\mathrm{err}}$; min possible Err on synthetic data
- сравнение СММ по rabiner
- Обучить модели со стационарными МЦ.
- Построить доверительные интервалы для параметров на основе SE.
- Ширина доверительного интервала в зависимости от объема выборки :)
- Потестить СММ на данных с заведомо высокой автокорреляцией
- interpolation for multinomial HMMs
- init via k-means not only for MNorm; also other types of init
- RMSE?